site_name: jpferreira
repo_url: https://github.com/jpferreira/readthedocs
site_favicon: favicon.ico
copyright: "Copyright (C) 2017"
docs_dir: docs

pages:
- Introdução: index.md
- Instalacao e Configuração:
    - Instalação: instalacaoEConfiguracao/Instalacao.md

theme: readthedocs
